### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by LudoLoops** [neuromorph/custom-osd#11]
Hi, i have almost done the french Translation, i need to do some testing.
On what branch should I push the code?

**Comment by neuromorph** [comment]
Hello,
Thanks a lot for choosing to contribute. Unfortunately, I did not get a notification for this issue due to some prob with the repo (fixed now). Apologies for the tardy reply.
> On what branch should I push the code?

Please push on the 'main' branch. I will propagate further. (FYI, 'main' is for Gnome 45+ and 'g42-44' is for Gnome 42-44). 

Also, there were some changes introduced in the latest update e.g. Progress Ring, paddings etc. I have thus updated the .pot file in the [main branch here](https://github.com/neuromorph/custom-osd/blob/main/po/custom-osd%40neuromorph.pot). It will be great if you can reconcile your translation with this updated pot. Most of it should be same with some changes and new strings for new settings. [This link ](https://stacktuts.com/how-to-update-po-and-pot-files-after-the-source-is-modified-in-gettext)provides steps to merge updated pot file into your po. Basically this command:
`msgmerge --update --backup=off id_ID.po custom-osd@neuromorph.pot`
This will enable complete translation in French. However, to reiterate from the ReadMe: 
> Ideally, a bare minimum would be to translate the functional UI part i.e. 'Profiles' and 'Settings' tabs UI even without the tooltips. This should already allow people to use the extension in their language.

 It is up to you though, I will also accept partial translations. I should have updated the .pot earlier, my bad. 

Thanks again! Let me know if you have any questions.

**Comment by LudoLoops** [comment]
ok, cool. 
I'll take a look about it.


btw I have also done this theme:
![image](https://github.com/neuromorph/custom-osd/assets/56033812/defd3c2b-abcc-4c1b-9ec3-946e729031cd)

i guess i can also push it on the main branch on another commit ?

**Comment by neuromorph** [comment]
OK. Cool theme! Yes, you can push the theme profile(s) as json files under `/presets` in 'main'.

**Comment by LudoLoops** [comment]
I have updated the translation, and push it i am not allowed to push on the main branch:  Permission to neuromorph/custom-osd.git denied

**Comment by neuromorph** [comment]
Oh, you are not to push directly to this repo :)

- Fork this repo (at least main branch). Then add your translation to your forked repo as a commit. You can add the theme file in another commit.
- Test your commits to see they work as intended (esp. translation, I would not be able to verify).
- Once you are ready with the commit(s), submit a PR (pull request) back to source (this repo).
- If all's well, I will merge the PR and then your commits will get added to this repo.

Thanks!

**Comment by LudoLoops** [comment]
yes it make sense to don't push it on main :D
