### ISSUE TITLE
Extension setting page not opening on Gnome 46

### ISSUE THREAD

**Issue by ibrahim0891** [neuromorph/custom-osd#13]
Hi there, 
Its been a long time i am using this extension. Till now everything was okay . But when i installed this extension after after upgrading to gnome 46 . I'm getting this following error.
```
Error: Requiring Json, version none: Typelib file for namespace 'Json' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Json/:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```
Hope this error would be fixed soon . Waiting for next update.
Thanks for making this awesome extension.

**Comment by neuromorph** [comment]
Hello,
Unfortunately, I did not get a notification for this issue due to some prob with the repo (fixed now). Apologies for the tardy reply.

This seems like an issue with your package installations esp. for Json. The settings for Custom OSD does use Json for Import/Export profiles. I have tested it in Gnome 46 with Gnome OS nightly and it is working as expected. What OS/version are you trying with?
To confirm the trace, can you pls use this command to monitor the journal and then try to open the extension settings. Paste the messages here.
`SHELL_DEBUG=all journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

Googling for similar errors w.r.t. Gnome, suggests updating system might help. 

> Thanks for making this awesome extension.

Thank you and you are welcome!

**Comment by ibrahim0891** [comment]
Hello , 
Hope you are doing well. I also apologise for late replay . 
Thank you so much for your reply. 
I have run the command you gave me . Then opened the settings. This time setting opened without any issue. Then i closed the terminal . After that the setting is opening perfectly. 
Once again , thank you !! 
Love your effort to make gnome wonderful!!

**Comment by neuromorph** [comment]
Thank you, appreciate it!

In case someone else is facing the issue, you can try updating your system and fixing any broken packages. The one needed here is GLib Json, something like libjson-glib-1.0. GLib Json is being used in the preferences for Import / Export of profiles in JSON format.
I did not need to install it specifically, but in case it is missing for your install.

Hope this helps.

**Comment by neuromorph** [comment]
UPDATE:
I found the issue when trying Ubuntu 24.04. This error happens due to missing introspection package. While the libjson-glib is installed by default as expected, the corresponding introspection package is missing for some reason. 

Anyone facing this issue, please install following tiny package to fix it. You can use synaptic package manager if you wish.
Package:  `gir1.2-json-1.0`

The 'gir' is the Gnome Introspection Repository. This helps it find the API for the lib already installed.

Thanks.
