### ISSUE TITLE
feature request(?): make the extension work when desktop is locked

### ISSUE THREAD

**Issue by ruxkbo** [neuromorph/custom-osd#5]
hi!
day 1 i installed the extension, it's so awesome!
why gnome devs can't include or make such ability as stock, thanks to you, we have this
but, i thought it'll work while the desktop is locked
like when trying to type the password, you'll get that tiny line that says your caps is locked
or the volume's osd

feel free to delete if this is a duplicate or already in your roadmap or mark this to which label it need to be

again thank you for creating this

`>ruxbo`

**Comment by neuromorph** [comment]
Missed the notification, I need to fix the github settings.
Thank you for appreciating, means a lot!
To the issue, I believe you mean that the extension is not applied when the screen is locked. While the default behavior is intact. Correct me if that's not the case. Default behavior meaning: you will get the tiny line saying caps is on, as usual, and you can also get the volume OSDs as usual. In short, the defaults are not affected, so there is no bug. 
However, the extension isn't active on lock screen and so you'll not get any customizations of Custom OSD. This is since the extension runs in 'User' mode and to operate on lock screen it needs a more privileged mode. I need to explain the need for such mode for this extension to Gnome reviewers and then I can get it to work there. 
I am marking it as 'enhancement' and will keep it here for now. You or anyone else who would prefer it to work on lock screen, feel free to add comment and any details here.
Finally, in case you are facing a bug like not getting the tiny caps on line, please report the Gnome version, OS and extension version.
Thanks.

**Comment by ruxkbo** [comment]
you're right, it's in session of the user using it

though i haven't tried it, isn't an extension can be installed system wide?

thank you and my apologies for not seeing your response, i just signed up here to say your extension is awesome!

will do, that i forgot to include in my comment the info of my version -- i'm using the latest, 44🤪

**Comment by neuromorph** [comment]
Thank you for taking time to sign up and comment here, I appreciate it.
Yes, the extension can actually be run in Session mode (if  published with it) instead of User mode to enable it on lock screen. However, Gnome discourages it and they need  some good reason to allow an extension in such case. For e.g. a Brightness control extension or one that alters lock screen should keep running etc. Anyway, if more users request it then I will take it up :+1: 

Thanks again, you can star this repo if you like to support. Also, new update for multiple profiles is pushed for Gnome 44 (not yet in 45). Hope it helps. 

Oh, if you use many extensions, you should look at [Extensions Glass Grid](https://extensions.gnome.org/extension/6269/extensions-glass-grid/), new extension :slightly_smiling_face:

**Comment by neuromorph** [comment]
@ruxbo 
Not sure how I missed to mention earlier. I got wrapped up in Gnome's rules for publishing.
Anyway, just want to convey that, you can yourself turn On session mode so that the extension works even on Lock screen for you. It is very easy, you need to add a line to the metadata.json file and re-login to see the effect.

The file is located at `~/.local/share/gnome-shell/extensions/custom-osd@neuromorph/metadata.json`
The line to add is : `"session-modes": ["user", "unlock-dialog"]` after adding comma to the last line showing version,
Complete example :

`{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Fully customize your OSD ( On Screen Display ) pop ups like Volume , Brightness or Caffeine , Lock Keys etc. Move, orient, resize, numeric %, choose monitor, set hide-delay and style to match your theme and liking. You can also select any combination of components to display: icon, text-label, level-bar, numeric %. ",  
  "donations": {
    "buymeacoffee": "neuromorph"
  },
  "gettext-domain": "custom-osd",
  "name": "Custom OSD",
  "settings-schema": "org.gnome.shell.extensions.custom-osd",
  "shell-version": [
    "42",
    "43",
    "44"
  ],
  "url": "https://github.com/neuromorph/custom-osd",
  "uuid": "custom-osd@neuromorph",
  "version": 17,
  "session-modes": ["user", "unlock-dialog"]
}`

**Comment by ruxkbo** [comment]
i'll try that later

thank you!

**Comment by ruxkbo** [comment]
> ["user", **"unlock-dialog"**]

that did it!
i applied it to the other ext as well-- lock keys
now all osd on locked are very pretty 👍
_i tend to lower the volume when it's locked 😁_

thank you
